[package]
name = "tetris"
version = "0.2.0"
authors = ["mike stedman <barbeque@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"

[dependencies.sdl2]
default-features = false
features = [ "ttf", "image" ]
version = "0.37"

