[package]
name = "tetris"
version = "0.1.0"
authors = ["mike stedman <barbeque@users.noreply.github.com>"]
edition = "2018"

[dependencies]

[dependencies.sdl2]
version = "0.31"
features = [ "use_mac_framework", "ttf" ]
